import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
	
	int twoChildrenCount = 0;
	int threeChildrenCount = 0;
	int fourAndMoreChildrenCount = 0; 
	int boyCounter = 0;
	int girlCounter = 0;
	int childrenCount = 0;
	double rnd = generator.nextDouble();
	
	for (int i = 0; i < T; i++){
		boolean boyBorn = false; 
		boolean girlBorn = false;
		while (boyBorn == false || girlBorn == false) { 
			if (rnd < 0.5) { 
				boyBorn = true;
				boyCounter++;
		} else {
			girlBorn = true;
			girlCounter++;
		}
		childrenCount++; 
		rnd = generator.nextDouble();
		}
		if (girlCounter + boyCounter == 2) {
			twoChildrenCount ++;
			}
		else if (girlCounter + boyCounter == 3) {
			threeChildrenCount ++;
		}
		else {
			fourAndMoreChildrenCount ++;
		}
		boyBorn = false;
		girlBorn = false;
		boyCounter = 0;
		girlCounter = 0;
		
	}
		System.out.println("Average: " + (childrenCount) / ((double) T) + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + (int)twoChildrenCount);
		System.out.println("Number of families with 3 children: " + (int)threeChildrenCount);
		System.out.println("Number of families with 4 or more children: " + (int)fourAndMoreChildrenCount);

		if ((twoChildrenCount > threeChildrenCount) && twoChildrenCount > fourAndMoreChildrenCount) {
			System.out.println("The most common number of children is 2."); 
		}
		else if (((threeChildrenCount > twoChildrenCount) && threeChildrenCount > fourAndMoreChildrenCount)) {
			System.out.println("The most common number of children is 3." ); 
		}
		else if (((fourAndMoreChildrenCount > threeChildrenCount) && fourAndMoreChildrenCount > twoChildrenCount)) {
			System.out.println("The most common number of children is 4 or more." );
		}
	}
}
