import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
	
	int totalChildren = 0;
	int twoChildrenCount = 0;
	int threeChildrenCount = 0;
	int fourAndMoreChildrenCount = 0; 
	String firstMostCommon = "";

	
	for (int i = 0; i < T; i++){
		int childrenCount = 0;
		boolean boyBorn = false; 
		boolean girlBorn = false;
		double rnd = generator.nextDouble();
		while (boyBorn == false || girlBorn == false) { 
			if (rnd < 0.5) { 
				boyBorn = true;
		} else {
			girlBorn = true;
		}
		childrenCount++; 
		rnd = generator.nextDouble();
		}
		totalChildren = totalChildren + childrenCount; 
		if (childrenCount == 2) {
			twoChildrenCount ++;
			firstMostCommon = firstMostCommon + "2"; }
		else if (childrenCount == 3) {
			threeChildrenCount ++;
			firstMostCommon = firstMostCommon + "3";
		}
		else {
			fourAndMoreChildrenCount ++;
			firstMostCommon = firstMostCommon + "4";
		}
		boyBorn = false;
		girlBorn = false;
	}
		System.out.println("Average: "+ (double) totalChildren/T + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + twoChildrenCount);
		System.out.println("Number of families with 3 children: " + threeChildrenCount);
		System.out.println("Number of families with 4 or more children: " + fourAndMoreChildrenCount);

		if (((twoChildrenCount > threeChildrenCount) && twoChildrenCount > fourAndMoreChildrenCount) || (firstMostCommon.charAt(0) == '2')) {
			System.out.println("The most common number of children is 2."); 
		}
		else if (((threeChildrenCount > twoChildrenCount) && threeChildrenCount > fourAndMoreChildrenCount) || (firstMostCommon.charAt(0) == '3')) {
			System.out.println("The most common number of children is 3." ); 
		}
		else if (((fourAndMoreChildrenCount > threeChildrenCount) && fourAndMoreChildrenCount > twoChildrenCount) || (firstMostCommon.charAt(0) == '4')) {
			System.out.println("The most common number of children is 4 or more." );
		}
	}
}
